---
# Bu, tüm ödevi yapan Ansible Playbook'udur
# Hedef: 'webservers' grubundaki tüm sunucular (yani .131 ve .132)
- hosts: webservers
  become: yes  # 'sudo' ile çalıştır
  tasks:

    # --- BÖLÜM 1: TEMEL KURULUMLAR (İKİ SUNUCUDA DA) ---
    - name: 1.1 - Paket listesini güncelle
      ansible.builtin.apt:
        update_cache: yes

    - name: 1.2 - Nginx kur
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: 1.3 - Keepalived kur
      ansible.builtin.apt:
        name: keepalived
        state: present

    - name: 1.4 - IP yönlendirmeyi (Sanal IP için) aktifleştir
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: yes

    # --- BÖLÜM 2: NGINX AYARLARI (Role Göre Farklı) ---
    - name: 2.1 - MASTER (Patron) sunucuya index.html dosyasını kopyala
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: '<h1>Ansible Tarafindan Kuruldu - WEBSUNUCU-1 (MASTER)</h1>'
      when: rol == 'master' # Sadece 'rol=master' olan sunucuda (yani .131'de) çalışır

    - name: 2.2 - BACKUP (Yedek) sunucuya index.html dosyasını kopyala
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: '<h1>Ansible Tarafindan Kuruldu - WEBSUNUCU-2 (BACKUP)</h1>'
      when: rol == 'backup' # Sadece 'rol=backup' olan sunucuda (yani .132'de) çalışır

    # --- BÖLÜM 3: KEEPALIVED AYARLARI (Role Göre Farklı) ---
    - name: 3.1 - MASTER (Patron) sunucuya keepalived.conf dosyasını kopyala
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_script chk_nginx {
              script "/usr/bin/pgrep nginx"
              interval 2
              weight -50
          }
          vrrp_instance VI_1 {
              state MASTER
              interface ens33
              virtual_router_id 51
              priority 101
              authentication {
                  auth_type PASS
                  auth_pass 1111
              }
              virtual_ipaddress {
                  {{ virtual_ip }}/24
              }
              track_script {
                  chk_nginx
              }
          }
      when: rol == 'master'
      notify: restart keepalived # Bu dosya değişirse 'keepalived' servisini yeniden başlat

    - name: 3.2 - BACKUP (Yedek) sunucuya keepalived.conf dosyasını kopyala
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_script chk_nginx {
              script "/usr/bin/pgrep nginx"
              interval 2
              weight -50
          }
          vrrp_instance VI_1 {
              state BACKUP
              interface ens33
              virtual_router_id 51
              priority 100
              authentication {
                  auth_type PASS
                  auth_pass 1111
              }
              virtual_ipaddress {
                  {{ virtual_ip }}/24
              }
              track_script {
                  chk_nginx
              }
          }
      when: rol == 'backup'
      notify: restart keepalived # Bu dosya değişirse 'keepalived' servisini yeniden başlat

    # --- BÖLÜM 4: YEDEKLEME AYARLARI (SADECE MASTER'DA) ---
    - name: 4.1 - Yedekleme klasörünü (/backup) oluştur
      ansible.builtin.file:
        path: /backup
        state: directory
        mode: '0755'
      when: rol == 'master'

    - name: 4.2 - Yedekleme script'ini (/usr/local/bin/gunluk_backup.sh) kopyala
      ansible.builtin.copy:
        dest: /usr/local/bin/gunluk_backup.sh
        mode: '0755' # Çalıştırılabilir yap (chmod +x)
        content: |
          #!/bin/bash
          BACKUP_DIR="/backup"
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
          BACKUP_NAME="backup-${TIMESTAMP}.tar.gz"
          sudo tar -czf ${BACKUP_DIR}/${BACKUP_NAME} -C /var/www/ html
          sudo find ${BACKUP_DIR} -name "backup-*.tar.gz" -type f -mtime +7 -exec rm {} \;
      when: rol == 'master'

    - name: 4.3 - Yedekleme için Cron (zamanlanmış görev) ekle
      ansible.builtin.cron:
        name: "Gecelik web sitesi yedeklemesi"
        minute: "0"
        hour: "2"
        job: "/usr/local/bin/gunluk_backup.sh > /backup/backup.log 2>&1"
      when: rol == 'master'

  # --- BÖLÜM 5: SERVİS YENİDEN BAŞLATMA ---
  # 'notify' komutu verildiğinde bu bölüm çalışır
  handlers:
    - name: restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
